# Funções de criação de arrays

O numpy conta com uma infinidade de funções para a criação de ndarrays, desde ndarrays baseados em intervalo até ndarrays com valores aleatórios.

# np.array( )

A função np.array retorna um array com base em uma sequência, os seus parâmetros:

**object:** uma sequência nativa do python; a função retornará um array com os elementos dessa sequência, que pode ser uma lista, uma tupla ou uma string.

**dtype:** define o tipo dos elementos que irão compor o array; não é um argumento obrigatório, o numpy detecta automaticamente o melhor tipo de dado para garantir que todos os elementos do array possuam o mesmo tipo de dado.

In [3]:
import numpy as np

numeros = [1,2,3,4,5]

numeros_array = np.array(numeros)

print(f"Array gerado com np.array(): {numeros_array}")

Array gerado com np.array(): [1 2 3 4 5]


# np.zeros( )

A função np.zeros retorna um array totalmente preenchido com zeros e possui os seguintes parâmetros:

**shape:** Define a forma do array de zeros; números inteiros criam arrays unidimensionais e tuplas com a partir de dois elementos criam arrays multidimensionais.

**dtype:** Define o tipo dos elementos que irão compor o array de zeros; não é um argumento obrigatório.

In [9]:
import numpy as np

zeros_array = np.zeros(10)

print(f"Array gerado com o np.zeros(): {zeros_array}")

Array gerado com o np.zeros(): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# np.ones( )

A função np.ones funciona de maneira semelhante ao np.zeros, a diferença é que esta gera um array preenchido com uns. O np.ones() possui os seguintes parâmetros:

**shape:** Define a forma do array de uns; valores inteiros retornam arrays unidimensionais e tuplas com a partir de dois elementos retornam arrays multidimensionais.

**dtype:** Define o tipo dos elementos que irão compor o array de uns; argumento não obrigatório, o numpy detecta automaticamente o melhor tipo de dado para os elementos do array.

In [10]:
import numpy as np

ones_array = np.ones((2,3))

print(f"Array gerado com o np.ones(): \n{ones_array}")

Array gerado com o np.ones(): 
[[1. 1. 1.]
 [1. 1. 1.]]


# np.zeros_like( )

A função np.zeros_like cria um array de zeros com a mesma forma e o mesmo tipo de dado do array de referência, possui os seguintes parâmetros:

**a:** o array de referência; a função cria um array com a mesma forma e tipo de dado deste array, mas preenchido com zeros.

In [13]:
import numpy as np

array_numeros = np.array([[1,2,3,4], [7, 8, 9, 0]])

array_zeros = np.zeros_like(array_numeros)

print(f"Array original de números: \n{array_numeros}\n")
print(f"Array de zeros com mesma forma e tipo de dados: \n{array_zeros}")


Array original de números: 
[[1 2 3 4]
 [7 8 9 0]]

Array de zeros com mesma forma e tipo de dados: 
[[0 0 0 0]
 [0 0 0 0]]


# np.ones_like( )

A função ones_like possui um funcionamento bem semelhante ao da função zeros_like, mas esta retorna um array de mesma forma e tipo de dados do array de diferença preenchido com uns, possui os seguintes parâmetros:

**a:** array de referência, a função cria um array de mesma forma e tipo de dado deste array, mas o array é preenchido com uns.



In [16]:
import numpy as np

array_letras = np.array([["a", "b", "c"], ["x", "y", "z"]])

array_uns = np.ones_like(array_letras)

print(f"Array original de letras: \n{array_letras}\n")
print(f"Array de uns com mesma forma e tipo de dados: \n{array_uns}")

Array original de letras: 
[['a' 'b' 'c']
 ['x' 'y' 'z']]

Array de uns com mesma forma e tipo de dados: 
[['1' '1' '1']
 ['1' '1' '1']]
